---
title: "Dockerfile"
toc: false
page-layout: full
number-sections: false
---

[← Back to workflow](../../ascat.html)

Container environment for the ASCAT-C wind workflow.

::: {.code-shell}

```{.dockerfile}
{{< include ../../workflows/ascat/Dockerfile >}}
```

:::
