project:
  type: book
  output-dir: docs

book:
  title: "CoastWatch West Coast node / SWFSC ERDDAP migration"
  author: "Jonathan Sherman"
  chapters:
    - index.qmd
    - viirs-netpp.qmd

format:
  html:
    theme: cosmo
    toc: true