---
title: "Dockerfile"
toc: false
page-layout: full
number-sections: false
---

[← Back to workflow](../../nsidc.html)

Container environment for the NSIDC sea ice workflow.

::: {.code-shell}

```{.dockerfile}
{{< include ../../workflows/nsidc/Dockerfile >}}
```

:::
