---
title: "Dockerfile"
toc: false
page-layout: full
number-sections: false
---

[← Back to workflow](../../mh1-primprod.html)

Container environment for the MODIS-Aqua MH1 primary productivity workflow.

::: {.code-shell}

```{.dockerfile}
{{< include ../../workflows/mh1-primprod/Dockerfile >}}
```

:::
